config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :publications
  devise_for :users, controllers: {
    sessions: "users/sessions", #FALTAMA UNA COMA NO TE CREO ANIMAL!!!!
    registrations: "users/registrations"
  }

  get 'homes/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "homes#index"
  get '/publications', to: 'publications#index', as: 'user_root' #mapache quesesooo
end

app/models/publication.rb
class Publication < ApplicationRecord
  belongs_to :user
  has_many :comments
end

app/controllers/publications_controller.rb
class PublicationsController < ApplicationController
  before_action :set_publication, only: %i[ show edit update destroy ]
  #before_action :authenticate_user!, except: [:index, :show] #Comprueba que el usuario esté autenticado
  before_action :authenticate_user!

  before_action only: [:new, :create] do #Restriccion 1
    authorize_request(["author", "admin"])
  end

  before_action only: [:edit, :update, :destroy] do #Restriccion 2
    authorize_request(["admin"])
  end

  # GET /publications or /publications.json
  def index
    @publications = Publication.all
  end

  # GET /publications/1 or /publications/1.json
  def show
  end

  # GET /publications/new
  def new
    @publication = Publication.new
  end

  # GET /publications/1/edit
  def edit
  end

  # POST /publications or /publications.json
  def create
    @publication = Publication.new(publication_params)
    @publication.user_id = current_user.id #Recibidor de parametros

    respond_to do |format|
      if @publication.save
        format.html { redirect_to publication_url(@publication), notice: "Publication was successfully created." }
        format.json { render :show, status: :created, location: @publication }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @publication.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /publications/1 or /publications/1.json
  def update
    respond_to do |format|
      if @publication.update(publication_params)
        format.html { redirect_to publication_url(@publication), notice: "Publication was successfully updated." }
        format.json { render :show, status: :ok, location: @publication }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @publication.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /publications/1 or /publications/1.json
  def destroy
    @publication.destroy

    respond_to do |format|
      format.html { redirect_to publications_url, notice: "Publication was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_publication
      @publication = Publication.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def publication_params
      params.require(:publication).permit(:image, :title, :description, :user_id)
    end
end

app/helpers/publications_helper.rb
module PublicationsHelper
end

app/views/publications/_form.html.erb
<%= form_with(model: publication) do |form| %>
  <% if publication.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(publication.errors.count, "error") %> prohibited this publication from being saved:</h2>

      <ul>
        <% publication.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :image, style: "display: block" %>
    <%= form.text_field :image %>
  </div>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/publications/_publication.html.erb
<div id="<%= dom_id publication %>">


  <p class="fw-bold display-3">
    <%= publication.title %>
  </p>

  <p>
    <%= image_tag publication.image, class: "col-4" %>
  </p>

  <p>
    <%= publication.description %>
  </p>

  <p>
    <strong>Por:</strong>
    <%= publication.user.name %>
  </p>

</div>

app/views/publications/edit.html.erb
<h1>Editing publication</h1>

<%= render "form", publication: @publication %>

<br>

<div>
  <%= link_to "Show this publication", @publication %> |
  <%= link_to "Back to publications", publications_path %>
</div>

app/views/publications/index.html.erb
<!-- <p style="color: green"><%= notice %></p> -->

<div id="publications">
  <% @publications.each do |publication| %>
    <div class="border my-5 px-5 py-4">
      <%= render publication %>
      <p>
        <%= link_to "Ver publicación", publication %>
      </p>
    </div>
  <% end %>
</div>

<%= link_to "Nueva publicación", new_publication_path %>

app/views/publications/new.html.erb
<h1>New publication</h1>

<%= render "form", publication: @publication %>

<br>

<div>
  <%= link_to "Back to publications", publications_path %>
</div>

app/views/publications/show.html.erb
<!-- <p style="color: green"><%= notice %></p> -->

<%= render @publication %>

<div>
  
  <%= link_to "Back to publications", publications_path %>

  <%if user_signed_in?%>
  
    <%if current_user.id == @publication.user_id%>
      <%= link_to "Edit this publication", edit_publication_path(@publication) %> |
      <%= button_to "Destroy this publication", @publication, method: :delete %>
    <%end%>
  <%end%>

</div>